vich_uploader:
  db_driver: orm

  mappings:
    video_vignette:
      uri_prefix:         '%uploads_path%'
      upload_destination: '%kernel.project_dir%/public/%uploads_path%'
    video_image:
      uri_prefix:         '%uploads_path%'
      upload_destination: '%kernel.project_dir%/public/%uploads_path%'
